### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by mbatchkarov** [CASM-Consulting/baleen#1]
Query with a missing ID:

```
wget http://0.0.0.0:3124/sussex/consume --post-data='data=[{"text":"Germany"}]' -qO-
```

results in 

```
2016-09-02 15:21:32,446 ERROR org.apache.uima - Thread: [Procesing Pipeline#1 Thread]::, message: Annotator processing failed.
org.apache.uima.analysis_engine.AnalysisEngineProcessException: Annotator processing failed.
    at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:401) ~[baleen-2.2.0-SNAPSHOT.jar:na]
    at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.processAndOutputNewCASes(PrimitiveAnalysisEngine_impl.java:309) ~[baleen-2.2.0-SNAPSHOT.jar:na]
    at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.process(AnalysisEngineImplBase.java:267) ~[baleen-2.2.0-SNAPSHOT.jar:na]
    at org.apache.uima.collection.impl.cpm.engine.ProcessingUnit.processNext(ProcessingUnit.java:893) [baleen-2.2.0-SNAPSHOT.jar:na]
    at org.apache.uima.collection.impl.cpm.engine.ProcessingUnit.run(ProcessingUnit.java:575) [baleen-2.2.0-SNAPSHOT.jar:na]
Caused by: java.lang.NullPointerException: null
    at uk.ac.susx.baleen.SussexDataStorage.isBatchDone(SussexDataStorage.java:76) ~[baleen-2.2.0-SNAPSHOT.jar:na]
    at uk.gov.dstl.baleen.consumers.HttpConsumer.doProcess(HttpConsumer.java:57) ~[baleen-2.2.0-SNAPSHOT.jar:na]
    at uk.gov.dstl.baleen.uima.BaleenAnnotator.process(BaleenAnnotator.java:81) ~[baleen-2.2.0-SNAPSHOT.jar:na]
    at org.apache.uima.analysis_component.JCasAnnotator_ImplBase.process(JCasAnnotator_ImplBase.java:48) ~[baleen-2.2.0-SNAPSHOT.jar:na]
    at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:385) ~[baleen-2.2.0-SNAPSHOT.jar:na]
    ... 4 common frames omitted
```

**Comment by mbatchkarov** [comment]
Closed by 9d853cb0f024ba4d2ee146be166bce8bbd2c4838
